name: Type Check
on: [pull_request]

jobs:
  ts:
    if: "!contains(github.event.pull_request.title, 'WIP!')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"
      - name: Run Type Check
        run: deno check
